plugins { id 'com.android.application' }

android {
    namespace 'ru.infa.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'ru.infa.mobile'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release { minifyEnabled false }
        debug { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
